apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zonos-oss-database
  namespace: ped-prod
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  bootstrap:
    initdb:
      database: zonos_oss
      owner: zonos_oss
      dataChecksums: true
      encoding: UTF8
  enableSuperuserAccess: true
  postgresql:
    parameters:
      checkpoint_timeout: "15min"
      max_connections: "64"
      max_locks_per_transaction: "64"
      random_page_cost: "1"
  replicationSlots:
    highAvailability:
      enabled: true
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
  storage:
    storageClass: data_vg
    size: 5Gi
